::: {.itenv #hodge-theory-ii-lemma-1.2.9 title="Lemma 1.2.9" latex="{Lemma 1.2.9}"}
Let $B$, $C$, $B'$, $C'$, $D$, and $E$ be sub-objects of $A$.
Suppose that
$$
  \begin{gathered}
    B'+C' = D
    \qquad B'\cap C' = E
  \\B\cap D \subset B'
    \qquad C\cap D \subset C'.
  \end{gathered}
$$
Then
$$
  ((B+B')\cap(C+C'))/E
  \simto ((B+D)\cap(C+D))/D.
$$
:::

::: {.proof}
To prove surjectivity, we write
$$
  \begin{aligned}
    ((B+B')\cap(C+C'))+D
    &= (((B+B')\cap(C+C'))+B')+C'
  \\&= ((B+B')\cap(C+C'+B'))+C'
  \\&= (B+B'+C')\cap(C+C'+B')
  \\&= (B+D)\cap(C+D).
  \end{aligned}
$$

To prove injectivity, we write
$$
  (B+B')\cap(C+C')\cap D
  = ((B+B')\cap D)\cap((C+C')\cap D).
$$
Since $B'\subset D$, we have
$$
  \begin{aligned}
    (B+B')\cap D
    &= (B\cap D)+B'
  \\&= B'
  \end{aligned}
$$
and similarly
$$
  (C+C')\cap D
  = C'
$$
and
$$
  \begin{aligned}
    (B+B')\cap(C+C')\cap D
    &= B'\cap C'
  \\&= E.
  \end{aligned}
$$
:::

This finishes the proof of [(1.2.8)](#hodge-theory-ii-lemma-1.2.8), noting that [(1.2.8)](#hodge-theory-ii-lemma-1.2.8) is equivalent to ($*_k$) for large $k$.

::: {.itenv #theorem-1.2.10 title="Theorem 1.2.10" latex="{Theorem 1.2.10}"}
Let $\mathscr{A}$ be an abelian category, and provisionally denote by $\mathscr{A}'$ the category of objects of $\mathscr{A}$ endowed with three opposite filtrations $W$, $F$, and $\overline{F}$.
The morphisms in $\mathscr{A}'$ are the morphisms of $\mathscr{A}$ that are compatible with the three filtrations.

i. $\mathscr{A}'$ is an abelian category.
ii. The kernel (resp. cokernel) of an arrow $f\colon A\to B$ in $\mathscr{A}'$ is the kernel (resp. cokernel) of $f$ in $\mathscr{A}$, endowed with the filtrations induced by those of $A$ (resp. the quotients of those of $B$).
iii. Every morphism $f\colon A\to B$ in $\mathscr{A}'$ is strictly compatible with the filtrations $W$, $F$, and $\overline{F}$;
  the morphism $\Gr_W(f)$ is compatible with the bigradings of $\Gr_W(A)$ and $\Gr_W(B)$;
  the morphisms $\Gr_F(f)$ and $\Gr_{\overline{F}}(f)$ are strictly compatible with the filtration induced by $W$.
iv. The "forget the filtrations" functors, $\Gr_W$, $\Gr_F$, and $\Gr_{\overline{F}}$, and
  $$
    \begin{gathered}
      \Gr_W\Gr_F
      \simeq \Gr_F\Gr_W
    \\\simeq \Gr_{\overline{F}}\Gr_F\Gr_W
    \\\simeq \Gr_{\overline{F}}\Gr_W
      \simeq \Gr_W\Gr_{\overline{F}}
    \end{gathered}
  $$
  from $\mathscr{A}'$ to $\mathscr{A}$ are exact.
:::

\oldpage{13}
Denote by $\sigma_0(p,q)$ and $\sigma_1(p,q)$ the sequences
$$
  \begin{aligned}
    \sigma_0(p,q)
    &= (p,q), (p,q), (p,q-1), (p,q-2), (p,q-3), \ldots
  \\\sigma_0(p,q)
    &= (p,q), (p,q), (p-1,q), (p-2,q), (p-3,q), \ldots
  \end{aligned}
$$
and, with the notation of [(1.2.8)](#hodge-theory-ii-lemma-1.2.8), set
$$
  A_i^{p,q}
  = A_{\sigma_i(p,q)}
  \qquad\text{(for }i=0,1\text{)}.
$$

If $f\colon A\to B$ is compatible with $W$, $F$, and $\overline{F}$, then we have
$$
  f(A_i^{p,q})
  \subset B_i^{p,q}
  \qquad\text{(for }i=0,1\text{)}.
\startverb\tag{1.2.10.1}\stopverb
$$
Claim (iii) then follows from the following lemma:

::: {.itenv #hodge-theory-ii-lemma-1.2.11 title="Lemma 1.2.11" latex="{Lemma 1.2.11}"}
The $A_i^{p,q}$ give a bigrading of $A$.
We have
$$
  W^n(A)
  = \sum_{n+p+q\leqslant 0} A_i^{p,q}
  \qquad\text{(for }i=0,1\text{)}
\startverb\tag{1.2.11.1}\stopverb
$$
$$
  F^p(A)
  = \sum_{p'\geqslant p} A_0^{p',q'}
\startverb\tag{1.2.11.2}\stopverb
$$
$$
  \overline{F}^q(A)
  = \sum_{q'\geqslant q} A_1^{p',q'}.
\startverb\tag{1.2.11.3}\stopverb
$$
:::

::: {.proof}
By symmetry, it suffices to prove the claims concerning $i=0$.
Set $A_0=\bigoplus A_0^{p,q}$ and define filtrations $W$ and $F$ on $A_0$ by the equations of [(1.2.11)](#hodge-theory-ii-lemma-1.2.11).
The canonical map $i$ from $A_0$ to $A$ is compatible with the filtrations $W$ and $F$.
Furthermore, by [(1.2.8)](#hodge-theory-ii-lemma-1.2.8), $\Gr_W(i)$ is an isomorphism, and induces isomorphisms of graded objects
$$
  \sum_{p+q=n} A_0^{p,q}
  \simto \Gr_W^{-n}(A)
  = \sum_{p+q=n} A^{p,q}.
\startverb\tag{1.2.11.4}\stopverb
$$
The morphism $i$ is thus an isomorphism, and the $A_0^{p,q}$ give a bigrading of $A$.

Equation (1.2.11.1) then says that $\Gr_W(i)$ is an isomorphism.
By (1.2.11.4), $\Gr_F\Gr_W(i)$ is an isomorphism, and thus so too are $\Gr_W\Gr_F(i)$ and $\Gr_F(i)$.
Equation (1.2.11.2) then follows.
:::

::: {.rmenv #hodge-theory-ii-1.2.12 title="1.2.12" latex="{1.2.12}"}
We now prove [(1.2.10)](#theorem-1.2.10).
Let $f\colon A\to B$ in $\mathscr{A}'$ and endow $K=\Ker(f)$ with the filtrations induced by those of $A$.
By [(1.2.11)](#hodge-theory-ii-lemma-1.2.11), $\Gr_W(K)\hookrightarrow\Gr_W(A)$;
furthermore, the filtration $F$ (resp. $\overline{F}$) on $K$ induces on $\Gr_W(K)$ the inverse image filtration of the filtration $F$ on $\Gr_W(A)$.
The sub-object $\Gr_W(K)$ of $\Gr_W(A)$ is then compatible with the bigrading of $\Gr_W(A)$:
$$
  \Gr_W(K)
  = \bigoplus_{p,q}(\Gr_W(K)\cap A^{p,q}).
$$

We thus deduce that
$$
  \Gr_F^p\Gr_{\overline{F}}^q\Gr_W^n(K)
  \hookrightarrow \Gr_F^p\Gr_{\overline{F}}^q\Gr_W^n(A);
$$
\oldpage{14}
the filtrations of $W$, $F$, and $\overline{F}$ on $K$ are thus opposite, and $K$ is a kernel of $f$ in $\mathscr{A}'$.
This, combined with the dual result, proves (ii).

If $f$ is an arrow of $\mathscr{A}'$, then the canonical morphism from $\Coim(f)$ to $\Im(f)$ is an isomorphism in $\mathscr{A}$;
by (iii), it is also an isomorphism in $\mathscr{A}'$, which is thus abelian.

The "forget the filtrations" functor is exact by (ii).
The exactness of the other functors in (iv) follows immediately from (ii), (iii), and [(1.1.11), (i) or (ii)](#hodge-theory-ii-proposition-1.1.11).
:::

::: {.rmenv #hodge-theory-ii-1.2.13 title="1.2.13" latex="{1.2.13}"}
Let $A$ be an object of $\mathscr{A}$ endowed with a finite *increasing* filtration $W_\bullet$, and two finite decreasing filtrations $F$ and $\overline{F}$.
The construction [(1.1.3)](#hodge-theory-ii-1.1.3) associates to $W_\bullet$ a decreasing filtration $W^\bullet$.
We say that the filtrations $W_\bullet$, $F$, and $\overline{F}$ are *opposite* if the filtrations $W^\bullet$, $F$, and $\overline{F}$ are, i.e. if, for all $n$, the filtrations induced by $F$ and $\overline{F}$ on
$$
  \Gr_n^W(A)
  = W_n(A)/W_{n-1}(A)
$$
are $n$-opposite.

Theorem [(1.2.10)](#theorem-1.2.10) translates trivially to this variation.
:::



















## The two filtrations lemma {#section-1.3}

::: {.rmenv #hodge-theory-ii-1.3.1 title="1.3.1" latex="{1.3.1}"}
Let $K$ be a differential complex of objects of $\mathscr{A}$, endowed with a filtration $F$.
The filtration is said to be *biregular* if it induces a finite filtration on each component of $K$.

We recall the definition of the terms $E_r^{pq}(K,F)$, or simply $E_r^{pq}$, of the spectral sequence defined by $F$.
We set
$$
  Z_r^{pq}
  = \Ker(d\colon F^p(K^{p+q})\to F^{p+q+1}/F^{p+r}(K^{p+q+1}))
$$
and dually we define $B_r^{pq}$ by the formula
$$
  K^{p+q}/B_r^{pq}
  = \Coker(d\colon F^{p-r+1}(K^{p+q+1})\to K^{p+q}/F^{p+1}(K^{p+q})).
$$
These formulas still make sense for $r=\infty$.

We note that the use here of the notation $B_r^{pq}$ is different to that of Godement [@15].

We have, by definition:
$$
  E_r^{pq}
  = \Im(Z_r^{pq}\to K^{p+q}/B_r^{pq})
\startverb\tag{1.3.1.1}\stopverb
$$
$$
  = Z_r^{pq}/(B_r^{pq}\cap Z_r^{pq})
\startverb\tag{1.3.1.2}\stopverb
$$
$$
  = \Ker(K^{p+q}/B_r^{pq}\to K^{p+q}/(Z_r^{pq}+B_r^{pq})).
\startverb\tag{1.3.1.3}\stopverb
$$
We can thus write
$$
  \begin{aligned}
    B_r^{p\bullet}\cap Z_r^{p\bullet}
    &\coloneqq (dF^{p-r+1}+F^{p+1}) \cap (d^{-1}F^{p+r}\cap F^p)
  \\&= (dF^{p-r+1}\cap F^p) + (F^{p+1}\cap d^{-1}F^{p+r})
  \end{aligned}
\startverb\tag{1.3.1.4}\stopverb
$$
since $dF^{p-r+1}\subset d^{-1}F^{p+r}$ and $F^{p+1}\subset F^p$.

\oldpage{15}
For $r<\infty$, the $E_r$ form a complex graded by the degree $p-r(p+q)$, and $E_{r+1}$ can be expressed as the cohomology of this complex:
$$
  E_{r+1}^{pq}
  = \HH(E_r^{p-r,q+r-1} \xrightarrow{d_r} E_r^{pq} \xrightarrow{d_r} E_r^{p+r,q-r+1}).
\startverb\tag{1.3.1.5}\stopverb
$$

For $r=0$, we have
$$
  E_0^{\bullet\bullet}
  = \Gr_F^\bullet(K^\bullet).
\startverb\tag{1.3.1.6}\stopverb
$$
:::

::: {.itenv #hodge-theory-ii-proposition-1.3.2 title="Proposition 1.3.2" latex="{Proposition 1.3.2}"}
Let $K$ be a complex endowed with a biregular filtration $F$.
The following conditions are equivalent:

i. The spectral sequence defined by $F$ degenerates ($E_1=E_\infty$).
ii. The morphisms $d\colon K^i\to K^{i+1}$ are strictly compatible with the filtrations.
:::

::: {.proof}
We will prove this in the case where $\mathscr{A}$ is a category of modules.
For fixed $p$ and $q$, the hypothesis that the arrows $d_r$ with domains $E_r^{pq}$ be zero for $r\geqslant1$ implies that, if $x\in F^p(K^{p+q})$ satisfies $dx\in F^{p+1}(K^{p+q+1})$, then there exists $y\in K^{p+q}$ such that $dy=0$ and such that $x$ and $y$ have the same image in $E_1^{pq}$.
Modifying $y$ by a boundary, and setting $z=x-y$, we then have
$$
  \forall x\in F^p(K^{p+q})
  \left[
    dx\in F^{p+1}(K^{p+q+1})
    \implies \exists z\text{ s.t. } z\in F^{p+1}(K^{p+q}) \text{ and } dz=dx
  \right]
$$
or, in other words,
$$
  F^{p+1}(K^{p+q+1}) \cap dF^p(K^{p+q})
  = dF^{p+1}(K^{p+q}).
\startverb\tag{1}\stopverb
$$

If this condition is satisfied for arbitrary $p$ and $q$, then by induction on $r$ we have
$$
  F^{p+r} \cap dF^p
  = dF^{p+r}
$$
which, for large $p+r$, can be written as
$$
  F^p \cap dK
  = dF^p.
\startverb\tag{2}\stopverb
$$

Claim (2) trivially implies (1), and is equivalent to (ii), which proves the proposition.
:::

::: {.rmenv #hodge-theory-ii-1.3.3 title="1.3.3" latex="{1.3.3}"}
If $(K,F)$ is a filtered complex, we denote by $\Dec(K)$ the complex $K$ endowed with the *shifted filtration*
$$
  \Dec(F)^p K^n
  = Z_1^{p+n,-p}.
$$

This filtration is compatible with the differentials:
$$
  \begin{aligned}
    dZ_1^{p+n,-p}
    &\subset F^{p+n+1}(K^{n+1}) \cap \Ker(d)
  \\&\subset Z_\infty^{p+n+1,-p}
  \\&\subset Z_1^{p+n+1,-p}.
  \end{aligned}
$$

Since
$$
  \begin{aligned}
    Z_1^{p+1+n,-p-1}
    &\subset F^{p+1+n}(K^n)
  \\&\subset B_1^{p+n,-p}
  \\&\subset Z_1^{p+n,-p}
  \end{aligned}
\startverb\tag{1.3.3.1}\stopverb
$$
the evident arrow from $Z_1^{p+n,-p}/Z_1^{p+1+n,-p-1}$ to $Z_1^{p+n,-p}/B_1^{p+n,-p}$ is a morphism
$$
  u\colon E_0^{p,n-p}(\Dec(K)) \to E_1^{p+n,-p}(K).
\startverb\tag{1.3.3.2}\stopverb
$$
:::

::: {.itenv #hodge-theory-ii-proposition-1.3.4 title="Proposition 1.3.4" latex="{Proposition 1.3.4}"}
—

i. The morphisms (1.3.3.2) form a morphism of graded complexes from $E_0(\Dec(K))$ to $E_1(K)$.
ii. This morphism induces an isomorphism on cohomology.
iii. It induces step-by-step (via (1.3.1.5)) isomorphisms of graded complexes $E_r(\Dec(K))\simto E_{r+1}(K)$ (for $r\geqslant1$).
:::

::: {.proof}
\oldpage{16}
Let $F'$ be the filtration on $K$ defined by
$$
  {F'}^p(K^n)
  = \Dec(F)^{p-n}(K^n)
  = Z_1^{p,n-p}.
$$
We trivially have isomorphisms
$$
  E_r^{p,n-p}(\Dec(K))
  = E_{r+1}^{p+n,-p}(K,F')
\startverb\tag{1.3.4.1}\stopverb
$$
that are compatible with the $d_r$ and with (1.3.1.5).
The map $u$ comes from (1.3.4.1) and from the identity map
$$
  (K,F') \to (K,F).
$$
This proves (i), and it remains to show that, for $r\geqslant2$,
$$
  E_r^{pq}(K,F')
  \simto E_r^{pq}(K,F).
$$
We have
$$
  \begin{aligned}
    Z_r^{pq}(K,F')
    &= Z_r^{pq}(K,F)
    \qquad\text{(for }r\geqslant1\text{)}
  \\Z_r^{pq}(K,F') \cap B_r^{pq}(K,F')
    &= Z_r^{pq}(K,F) \cap B_r^{pq}(K,F)
    \qquad\text{(for }r\geqslant2\text{)}
  \end{aligned}
$$
and we can then apply (1.3.1.2).
:::

::: {.rmenv #hodge-theory-ii-1.3.5 title="1.3.5" latex="{1.3.5}"}
The construction [(1.3.3)](#hodge-theory-ii-1.3.3) is not self-dual.
The dual construction consists of defining
$$
  \Dec^\bullet(F)^pK^n
  = B_1^{p+n-1,-p+1}.
$$
We then have morphisms
$$
  E_0^{p,n-p}(\Dec(K))
  \to E_1^{p+n,p}(K)
  \to E_0^{p,n-p}(\Dec^\bullet(K))
$$
and, for $r\geqslant1$, isomorphisms
$$
  E_r^{p,n-p}(\Dec(K))
  \simto E_{r+1}^{p+n,p}(K)
  \simto E_{r}^{p,n-p}(\Dec^\bullet(K)).
$$
:::

Recall that a morphism of complexes is said to be a *quasi-isomorphism* if it induces an isomorphism on cohomology.

::: {.rmenv #hodge-theory-ii-definition-1.3.6 title="Definition 1.3.6" latex="{Definition 1.3.6}"}
—

i. A morphism $f\colon(K,F)\to(K',F')$ of filtered complexes with biregular filtrations is a *filtered quasi-isomorphism* if $\Gr_F(f)$ is a quasi-isomorphism, i.e. if the $E_1^{pq}(f)$ are isomorphisms.
ii. A morphism $f\colon(K,F,W)\to(K,F',W')$ of biregular bifiltered complexes is a *bifiltered quasi-isomorphism* if $\Gr_F\Gr_W(f)$ is a quasi-isomorphism.
:::

::: {.rmenv #hodge-theory-ii-1.3.7 title="1.3.7" latex="{1.3.7}"}
Let $K$ be a differential complex of objects of $\mathscr{A}$, endowed with two filtrations $F$ and $W$.
Let $E_r^{pq}$ be the spectral sequence defined by $W$.
The filtration $F$ induces on $E_r^{pq}$ various filtrations, which we will compare.
:::

::: {.rmenv #hodge-theory-ii-1.3.8 title="1.3.8" latex="{1.3.8}"}
Equation (1.3.1.2) identifies $E_r^{pq}$ with a quotient of a sub-object of $K^{p+q}$.
The $E_r^{pq}$ term is thusly given by endowing with a filtration $F_d$ induced by $F$, called the *first direct filtration*.
:::

::: {.rmenv #hodge-theory-ii-1.3.9 title="1.3.9" latex="{1.3.9}"}
Dually, Equation (1.3.1.3) identifies $E_r^{pq}$ with a sub-object of a quotient of $K^{p+q}$, whence a new filtration $F_{d^*}$ induced by $F$, called the *second direct filtration*.
:::

::: {.itenv #hodge-theory-ii-lemma-1.3.10 title="Lemma 1.3.10" latex="{Lemma 1.3.10}"}
\oldpage{17}
On $E_0$ and $E_1$, we have $F_d=F_{d^*}$.
:::

::: {.proof}
For $r=0,1$, we have $B_r^{pq}\subset Z_r^{pq}$, and we apply (1.1.9).
:::

::: {.rmenv #hodge-theory-ii-1.3.11 title="1.3.11" latex="{1.3.11}"}
Equation (1.3.1.5) identifies $E_{r+1}^{pq}$ with a quotient of a sub-object of $E_r^{pq}$.
We define the *recurrent filtration* $F_r$ on the $E_r^{pq}$ by the conditions

i. On $E_0^{pq}$, $F_r=F_d=F_{d^*}$.
ii. On $E_{r+1}^{pq}$, the recurrent filtration is that induced by the recurrent filtration of $E_r^{pq}$.
:::

::: {.rmenv #hodge-theory-ii-1.3.12 title="1.3.12" latex="{1.3.12}"}
Definitions [(1.3.8)](#hodge-theory-ii-1.3.8) and [(1.3.9)](#hodge-theory-ii-1.3.9) still make sense for $r=\infty$.
If the filtration on $K$ is biregular, then the direct filtrations on $E_\infty^{pq}$ coincide with those on $E_r^{pq}=E_\infty^{pq}$ for large enough $r$, and we define the recurrent filtration on $E_\infty^{pq}$ as agreeing with that on $E_r^{pq}$ for large enough $r$.

The filtrations $F$ and $W$ each induce a filtration on $H^\bullet(K)$, and $E_\infty^{\bullet\bullet}=\Gr_W^\bullet(\HH^\bullet(K))$.
The filtration $F$ on $\HH^\bullet(K)$ then induces on $E_\infty^{pq}$ a new filtration.
:::

::: {.itenv #hodge-theory-ii-proposition-1.3.13 title="Proposition 1.3.13" latex="{Proposition 1.3.13}"}
—

i. For the first direct filtration, the morphisms $d_r$ are compatible with the filtrations.
  If $E_{r+1}^{pq}$ is considered as a quotient of a sub-object of $E_r^{pq}$, then the first direct filtration on $E_{r+1}^{pq}$ is finer than the filtration $F'$ induced by the first direct filtration on $E_r^{pq}$Y we have $F_d(E_{r+1}^{pq})\subset F'(E_{r+1}^{pq})$.
ii. Dually, the morphisms $d_r$ are compatible with the second direct filtration, and the second direct filtration on $E_{r+1}^{pq}$ is less fine than the filtration induced by that of $E_r^{pq}$.
iii. $F_d(E_r^{pq})\subset F_r(E_r^{pq})\subset F_{d^*}(E_r^{pq})$.
iv. On $E_\infty^{pq}$, the filtration induced by the filtration $F$ of $\HH^\bullet(K)$ [(1.3.12)](#hodge-theory-ii-1.3.12) is finer than the first direct filtration and less fine than the second.
:::

::: {.proof}
Claim (i) is evident, (ii) is its dual, and (iii) follows by induction.
The first claim of (iv) is easy to verify, and the second is its dual.
:::

::: {.rmenv #hodge-theory-ii-1.3.14 title="1.3.14" latex="{1.3.14}"}
We denote by $\Dec(K)$ (resp. $\Dec^\bullet(K)$) the complex $K$ endowed with the filtrations $\Dec(W)$ and $F$ (resp. $\Dec^\bullet(W)$ and $F$).

It is clear by (1.3.4.1) that the isomorphism [(1.3.4)](#hodge-theory-ii-proposition-1.3.4) sends the first direct filtration on $E_r(\Dec(K))$ to the second direct filtration on $E_{r+1}(K)$ (for $r\geqslant1$).
The dual isomorphism [(1.3.5)](#hodge-theory-ii-1.3.5) sends the second direct filtration on $E_r(\Dec^\bullet(K))$ to the second direct filtration on $E_{r+1}(K)$.
:::

::: {.itenv #hodge-theory-ii-lemma-1.3.15 title="Lemma 1.3.15" latex="{Lemma 1.3.15}"}
If the filtration $F$ is biregular, and if, on the $\Gr_W^p(K)$, the morphisms $d$ are strictly compatible with the filtration induced by $F$, then

i. The morphism (1.3.3.2) of graded complexes filtered by $F$
  $$
    u\colon \Gr_{\Dec(W)}(K)
    \to E_1(K,W)
  $$
  is a filtered quasi-isomorphism.
ii. Dually, the morphism [(1.3.5)](#hodge-theory-ii-1.3.5)
  $$
    u\colon E_1(K,W)
    \to \Gr_{\Dec^\bullet(W)}(K)
  $$
  is a filtered quasi-isomorphism.
:::

::: {.proof}
It suffices, by duality, to prove (i).

\oldpage{18}
By [(1.3.3)](#hodge-theory-ii-1.3.3) and [(1.3.4)](#hodge-theory-ii-proposition-1.3.4), the complex $E_1(K,W)$ filtered by $F$ is a quotient of the filtered complex $\Gr_{\Dec(W)}(K)$.
Let $U$ be the filtered complex given by the kernel, which is acyclic by [(1.3.4), (ii)](#hodge-theory-ii-proposition-1.3.4).
The long exact sequence in cohomology associated to the exact sequence of complexes
$$
  0
  \to \Gr_F(U)
  \to \Gr_F(\Gr_{\Dec(W)}(K))
  \to \Gr_F(E_1(K,W))
  \to 0
$$
shows that $u$ is a filtered quasi-isomorphism if and only if $\Gr_F(U)$ is an acyclic complex.
By [(1.3.2)](#hodge-theory-ii-proposition-1.3.2), and since $U$ is acyclic, this reduces to asking that the differentials of $U$ be strictly compatible with the filtration $F$.
From (1.3.3.1) we obtain that $U$ is the sum over $p$ of the complexes
$$
  (U^p)^n
  = B_1^{p+n,-p}/Z_1^{p+1+n,-p-1}
$$
endowed with the filtration induced by $F$.

Each differential $d$ of each of the complexes $U^p$ fits into a commutative diagram of filtered objects of the following type, where, for simplicity, we have omitted the total or complementary degree:
**!!TO-DO: diagram!!**
By hypothesis, the morphism $(1)$ is strict.
Since the square $(2)$ is exactly the canonical decomposition of $(1)$, the arrow $(3)$ is a filtered isomorphism.
The arrows of the trapezium $(4)$ are isomorphisms;
they are thus filtered isomorphisms, since $(3)$ is a filtered isomorphism.
The fact that $(5)$ is a filtered isomorphism implies that $d$ is strict.
This proves the lemma.
:::

::: {.itenv #theorem-1.3.16 title="Theorem 1.3.16" latex="{Theorem 1.3.16}"}
Let $K$ be a complex endowed with two filtrations, $W$ and $F$, with the filtration $F$ biregular.
Let $r_0\geqslant0$ be an integer, and suppose that, for $0\leqslant r<r_0$, the differentials of the graded complex $E_r(K,W)$ are strictly compatible with the filtration $F$.
Then, for $r\leqslant r_0+1$, $F_d=F_r=F_{d^*}$ on $E_r^{pq}$.
:::

::: {.proof}
We will prove the theorem by induction on $r_0$.
For $r_0=0$, the hypothesis is empty, and we apply [(1.3.10)](#hodge-theory-ii-lemma-1.3.10) and [(1.3.13), (iii)](#hodge-theory-ii-proposition-1.3.13).
For $r_0\geqslant1$, by the inductive hypothesis, we have $F_d=F_r=F_{d^*}$ on $E_r^{pq}$ for $r\leqslant r_0$.

\oldpage{19}
By [(1.3.15)](#hodge-theory-ii-lemma-1.3.15), the morphism $u\colon E_0(\Dec(K))\to E_1(K)$ is a filtered quasi-isomorphism.
It thus induces a filtered isomorphism from $\HH^\bullet(\Dec(K))$ to $\HH^\bullet(E_1(K))$:
$$
  u\colon (E_1(\Dec(K)),F_r)
  \simto (E_2(K),F_r).
$$
Step-by-step, we thus deduce that the canonical isomorphism from $E_s(\Dec(K))$ to $E_{s+1}$ (for $s\geqslant1$) is a filtered isomorphism for the recurrent filtration.

On $E_1(\Dec(K))$, $F_r=F_d$ [(1.3.10)](#hodge-theory-ii-lemma-1.3.10), and we already know [(1.3.14)](#hodge-theory-ii-1.3.14) that $u'$ is a filtered isomorphism
$$
  u'\colon (E_1(\Dec(K)),F_d)
  \simto (E_2(K),F_d).
$$

On $E_2(K)$, we thus have $F_d=F_r$.
This, combined with the dual result, proves the theorem for $r_0=1$.

Suppose that $r_0\geqslant2$.
Then the arrows $d_1$ of $E_1(K)$ are strictly compatible with the filtrations, and thus so too are the arrows $d_0$ of $E_0(\Dec(K))$ (indeed, $u$ induces an isomorphism of spectral sequences, and we apply criterion [(1.3.2)](#hodge-theory-ii-proposition-1.3.2)).

For $0<s<r_0-1$, the isomorphism $(E_s(\Dec(K)),F_r)\cong(E_{s+1}(K),F_r)$ shows that the $d_s$ are strictly compatible with the recurrent filtrations.

By the induction hypothesis, we thus have $F_d=F_r$ on $E_s(\Dec(K))$ for $s\leqslant s_0$.
The isomorphism $(E_s(\Dec(K)),F_d)\cong(E_{s+1}(K),F_d)$ [(1.3.13)](#hodge-theory-ii-proposition-1.3.13) then shows that $F_d=F_r$ on $E_r(K)$ for $r\leqslant r_0+1$.
This, combined with the dual result, proves the theorem.
:::

::: {.itenv #corollary-1.3.17 title="Corollary 1.3.17" latex="{Corollary 1.3.17}"}
Under the general hypotheses of [(1.3.16)](#theorem-1.3.16), suppose that, for all $r$, the differentials $d_r$ are strictly compatible with the recurrent filtrations on the $E_r$.
Then, on $E_\infty$, the filtrations $F_d$, $F_r$, and $F_{d^*}$ agree, and coincide with the filtration induced by the filtration $F$ of $\HH^\bullet(K)$.
:::

::: {.proof}
This follows immediately from [(1.3.16)](#theorem-1.3.16) and [(1.3.13), (iv)](#hodge-theory-ii-proposition-1.3.13).
:::

















## Hypercohomology of filtered complexes {#section-1.4}

In this section, we recall some standard constructions in hypercohomology.
We do not use the language of derived categories, which would be more natural here.

*Throughout this entire section, by "complex" we mean "bounded-below complex".*

::: {.rmenv #hodge-theory-ii-1.4.1 title="1.4.1" latex="{1.4.1}"}
Let $T$ be a left-exact functor from an abelian category $\mathscr{A}$ to an abelian category $\mathscr{B}$.
Suppose that every object of $\mathscr{A}$ injects into an injective object;
the derived functors $\RR^iT\colon\mathscr{A}\to\mathscr{B}$ are then defined.
An object $A$ of $\mathscr{A}$ is said to be *acyclic* for $T$ if $\RR^iT(A)=0$ for $i>0$.
:::

::: {.rmenv #hodge-theory-ii-1.4.2 title="1.4.2" latex="{1.4.2}"}
Let $(A,F)$ be a filtered object with finite filtration, and $TF$ the filtration of $TA$ by its sub-objects $TF^p(A)$ (these are sub-objects since $T$ is left exact).
If $\Gr_F(A)$ is $T$-acyclic, then the $F^p(A)$ are $T$-acyclic as successive extensions of $T$-acyclic objects.
The image under $T$ of the sequence
$$
  0
  \to F^{p+1}(A)
  \to F^p(A)
  \to \Gr^p(A)
  \to 0
$$
\oldpage{20}
is thus exact, and
$$
  \Gr_{FT}TA \simto T\Gr_FA.
\startverb\tag{1.4.2.1}\stopverb
$$
:::

::: {.rmenv #hodge-theory-ii-1.4.3 title="1.4.3" latex="{1.4.3}"}
Let $A$ be an object endowed with finite filtrations $F$ and $W$ such that $\Gr_F\Gr_W A$ are $T$-acyclic.
The objects $\Gr_FA$ and $\Gr_WA$ are then $T$-acyclic, as well as the $F^q(A)\cap W^p(A)$.
The sequences
$$
  0
  \to T(F^q\cap W^{p+1})
  \to T(F^q\cap W^p)
  \to T((F^q\cap W^p)/(F^q\cap W^{p+1}))
  \to 0
$$
are thus exact, and $T(F^q(\Gr_W^p(A)))$ is the image in $T(\Gr_W^p(A))$ of $T(F^p\cap W^q)$.
The diagram
$$
  \begin{CD}
    T(F^q\cap W^p) @>>> T(F^q\Gr_W^pA) @>>> T\Gr_W^pA
  \\@V{\cong}VV @. @VV{\cong}V
  \\TF^q\cap TW^p @= TF^q\cap TW^p @>>> \Gr_{TW}^pTA
  \end{CD}
$$
then shows that the isomorphism (1.4.2.1) relative to $W$ sends the filtration $\Gr_{TW}(TF)$ to the filtration $T(\Gr_W(F))$.
:::

::: {.rmenv #hodge-theory-ii-1.4.4 title="1.4.4" latex="{1.4.4}"}
Let $K$ be a complex of objects of $\mathscr{A}$.
The *hypercohomology objects* $\RR^iT(K)$ are calculated as follows:

a. We choose a quasi-isomorphism $i\colon K\to K$ such that the components of $K'$ are acyclic for $T$.
  For example, we can take $K'$ to be the simple complex associated to an injective Cartan--Eilenberg resolution of $K$.
b. We set
  $$
    \RR^iT(K)
    = \HH^i(T(K')).
  $$

We can show that $\RR^iT(K)$ does not depend on the choice of $K'$, but depends functorially on $K$, and that a quasi-isomorphism $f\colon K_1\to K_2$ induces *isomorphisms*
$$
  \RR^iT(f)\colon
  \RR^iT(K_1)
  \to \RR^iT(K_2).
$$
:::

::: {.rmenv #hodge-theory-ii-1.4.5 title="1.4.5" latex="{1.4.5}"}
Let $F$ be a biregular filtration of $K$.
A *$T$-acyclic filtered resolution* of $K$ is a filtered quasi-isomorphism $i\colon K\to K'$ from $K$ to a filtered biregular complex such that the $\Gr^p({K'}^n)$ are acyclic for $T$.
If $K'$ is such a resolution, then the ${K'}^n$ are acyclic for $T$, and the filtered complex (cf. [(1.4.2)](#hodge-theory-ii-1.4.2)) $T(K')$ defines a spectral sequence
$$
  E_1^{pq}
  = \RR^{p+q}T(\Gr^p(K))
  \Rightarrow \RR^{p+q}T(K).
$$
This is independent of the choice of $K'$.
We call this the *hypercohomology spectral sequence of the filtered complex $K$*.
It depends functorially on $K$, and a filtered quasi-isomorphism induces an isomorphism of spectral sequences.

\oldpage{21}
The differentials $d_1$ of this spectral sequence are the connection morphisms defined by the short exact sequences
$$
  0
  \to \Gr^{p+1}K
  \to F^pK/F^{p+2}K
  \to \Gr^pK
  \to 0.
$$
:::

::: {.rmenv #hodge-theory-ii-1.4.6 title="1.4.6" latex="{1.4.6}"}
Let $K$ be a complex.
We denote by $\tau_{\leqslant p}(K)$ the following subcomplex:
$$
  \tau_{\leqslant p}(K)^n
  = \begin{cases}
    K^n
    &\text{for }n<p
  \\\Ker(d)
    &\text{for }n=p
  \\0
    &\text{for }n>p.
  \end{cases}
$$

The *filtration*, said to be *canonical*, of $K$ by the $\tau_{\leqslant p}(K)$ is induced by shifting the trivial filtration $G$ for which $G^0(K)=K$ and $G^1(K)=0$.
We have, for the canonical filtration,
$$
  \begin{aligned}
    E_1^{pq} = 0
    &\qquad\text{if }p+q\neq-p
  \\\\H^{-p}
    &\qquad\text{if }p+q=-p.
  \end{aligned}
$$
A quasi-isomorphism $f\colon K\to K'$ is automatically a filtered quasi-isomorphism for the canonical filtrations.
:::

::: {.rmenv #hodge-theory-ii-1.4.7 title="1.4.7" latex="{1.4.7}"}
The subcomplexes $\sigma_{\geqslant p}(K)$ of $K$
$$
  \sigma_{\geqslant p}(K)^n
  = \begin{cases}
    0
    &\text{if }n<p
  \\K^n
    &\text{if }n\geqslant p
  \end{cases}
$$
define a biregular filtration, called the *stupid filtration* of $K$.

The hypercohomology spectral sequences attached to the stupid or canonical filtrations of $K$ are the two *hypercohomology spectral sequences* of $K$.
:::

::: {.rmenv #hodge-theory-ii-1.4.8 title="Example 1.4.8" latex="{Example 1.4.8}"}
Let $f\colon X\to Y$ be a continuous map between topological spaces, and let $\mathscr{F}$ be an abelian sheaf on $X$.
Let $\mathscr{F}^\bullet$ be a resolution of $\mathscr{F}$ by $f_*$-acyclic sheaves.
We have $\RR^i f_*\mathscr{F}\simeq\sHH^i(f_*\mathscr{F}^\bullet)$.
We take the functor $T$ to be the functor $\Gamma(Y,-)$.
The hypercohomology spectral sequence of the complex $f_*\mathscr{F}^\bullet$ endowed with its canonical filtration (1.4.6)
$$
  E_1^{pq}
  = \HH^{2p+q}(Y,\RR^{-p}f_*\mathscr{F})
  \Rightarrow \HH^{p+q}(X,\mathscr{F})
$$
is exactly, up to the renumbering $E_r^{pq}\mapsto E_{r+1}^{2p+q,-p}$, the *Leray spectral sequence* for $f$ and $\mathscr{F}$.
:::

::: {.rmenv #hodge-theory-ii-1.4.9 title="1.4.9" latex="{1.4.9}"}
Let
:::
